# Azure Pipelines: build the Webclient

trigger:
  # Note that this pipeline will still run on pull requests. However,
  # operations that require service connections -- namely the AzureFileCopy --
  # will be skipped on PR builds, so randos can't just update our website by
  # submitting a PR.
  branches:
    include:
      - rebuild  # temporary!!! (?)

pool:
  # We need to run on Windows to take advantage of the AzureFileCopy@3 task.
  vmImage: 'windows-latest'

steps:
- task: Npm@1
  displayName: NPM install
  inputs:
    command: 'install'

- task: Grunt@0
  displayName: Build distribution directory with Grunt
  inputs:
    gruntFile: 'Gruntfile.js'
    targets: 'dist-prod'  # TEMPORARY: should differ depending on dev/prod

- task: CopyFiles@2
  displayName: Copy dist directory to artifact staging
  inputs:
    sourceFolder: '$(build.sourcesDirectory)/dist'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishPipelineArtifact@1
  displayName: Publish web deployment artifacts
  inputs:
    targetPath: '$(build.artifactStagingDirectory)'
    publishLocation: 'pipeline'
    artifactName: wwt-webclient-deployment

- task: AzureFileCopy@3
  displayName: Publish artifacts to Azure Blob storage
  inputs:
    SourcePath: '$(build.artifactStagingDirectory)'
    azureSubscription: 'aas@wwtadmindotnetfoundation'
    Destination: 'AzureBlob'
    storage: 'wwtwebstatic'
    ContainerName: '$web'
    blobPrefix: 'webclient'

# For annoying reasons, we have to include a default.aspx file that does a
# JavaScript redirection. In order for that to work, we have to tell the web
# server to serve up the file with a non-default "text/html" Content-Type.
# This task does the setting. Note that the azureSubscription account needs
# to be set up with the "Storage Blob Data Contribtor" role on the storage
# account in order for this to work.

- task: AzurePowerShell@4
  displayName: Update Azure Blob storage content types
  inputs:
    azureSubscription: 'aas@wwtadmindotnetfoundation'
    azurePowerShellVersion: 'LatestVersion'
    scriptType: 'inlineScript'
    inline: |
      Set-PSDebug -Trace 2
      $ctxt = New-AzStorageContext -UseConnectedAccount -StorageAccountName "wwtwebstatic"
      $ctxt
      $blob = Get-AzStorageBlob -Context $ctxt -Container '$web' -Blob "webclient/default.aspx"
      $blob
      $blob.ICloudBlob.properties.ContentType = "text/html"
      $blob.ICloudBlob.SetProperties()
